name: GH-Test-Acceptance
on:
  workflow_dispatch:
  
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: 1.20.2

      - name: Build gh validator
        run: go build ./main.go

      - name: Run gh validator secrets checks
        run: ./main
        env:
          STOREGH_TEST_TYPE: ${{ secrets.STOREGH_TEST_TYPE }}
          STOREGH_TEST_UUID: ${{ secrets.STOREGH_TEST_UUID }}
          STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_LOAD_KEY_1_BAD_SYMBOLS________: ${{ secrets[format('STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_LOAD_KEY_1_BAD_SYMBOLS________{0}', secrets.STOREGH_TEST_UUID)] }}
          STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_LOAD_KEY_2: ${{ secrets[format('STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_LOAD_KEY_2{0}', secrets.STOREGH_TEST_UUID)] }}
          STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_LOAD_KEY_3: ${{ secrets[format('STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_LOAD_KEY_3{0}', secrets.STOREGH_TEST_UUID)] }}
          STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_LOAD_KEY_4: ${{ secrets[format('STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_LOAD_KEY_4{0}', secrets.STOREGH_TEST_UUID)] }}
          STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_LOAD_KEY_5: ${{ secrets[format('STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_LOAD_KEY_5{0}', secrets.STOREGH_TEST_UUID)] }}
          STOREGH_REPOSITORY_ACTIONS_TEST_APP_LOAD_KEY_1: ${{ secrets[format('STOREGH_REPOSITORY_ACTIONS_TEST_APP_LOAD_KEY_1{0}', secrets.STOREGH_TEST_UUID)] }}
          STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_UPDATE_KEY_1: ${{ secrets[format('STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_UPDATE_KEY_1{0}', secrets.STOREGH_TEST_UUID)] }}
          STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_UPDATE_KEY_2: ${{ secrets[format('STOREGH_REPOSITORY_ACTIONS_TEST_TOKEN_UPDATE_KEY_2{0}', secrets.STOREGH_TEST_UUID)] }}
          STOREGH_REPOSITORY_ACTIONS_TEST_APP_UPDATE_KEY_1: ${{ secrets[format('STOREGH_REPOSITORY_ACTIONS_TEST_APP_UPDATE_KEY_1{0}', secrets.STOREGH_TEST_UUID)] }}
